import type { Photo, PhotoCategory } from './types';

export const photos: Photo[] = [
    {
        id: 1,
        src: '/ankit_images/20231123_0178.JPG',
        title: 'Against the Peaks',
        category: 'travel',
        description: 'Standing tall against the Himalayan backdrop, Pokhara',
        aspectRatio: '3:4',
    },
    {
        id: 2,
        src: '/ankit_images/20231123_0331.JPG',
        title: 'Annapurna Range',
        category: 'nature',
        description: 'The mighty Annapurna massif from Pokhara valley',
        aspectRatio: '4:3',
    },
    {
        id: 3,
        src: '/ankit_images/IMG_0479.JPG',
        title: 'Still Waters',
        category: 'nature',
        description: 'Calm blue waters reflecting the endless sky',
        aspectRatio: '3:4',
    },
    {
        id: 4,
        src: '/ankit_images/IMG_3406.jpg',
        title: 'Open Horizon',
        category: 'nature',
        description: 'Where the earth meets the endless blue',
        aspectRatio: '4:3',
    },
    {
        id: 5,
        src: '/ankit_images/IMG_3408 2.JPG',
        title: 'Turquoise Depths',
        category: 'nature',
        description: 'Nature painted in shades of teal and emerald',
        aspectRatio: '4:3',
    },
    {
        id: 6,
        src: '/ankit_images/IMG_5335.JPG',
        title: 'Night Whispers',
        category: 'moody',
        description: 'A quiet moment in the warmth of low light',
        aspectRatio: '3:4',
    },
    {
        id: 7,
        src: '/ankit_images/IMG_6967.jpg',
        title: 'Reaching Skyward',
        category: 'travel',
        description: 'Vertical grandeur captured in a single frame',
        aspectRatio: '2:3',
    },
    {
        id: 8,
        src: '/ankit_images/IMG_7013_jpg.JPG',
        title: 'Lakeside Dusk',
        category: 'nature',
        description: 'Golden hour painting the lake in warm hues',
        aspectRatio: '4:3',
    },
    {
        id: 9,
        src: '/ankit_images/IMG_7074.JPG',
        title: 'Panoramic Nepal',
        category: 'travel',
        description: 'A sweeping view of mountains and sky in panorama',
        aspectRatio: '4:3',
    },
    {
        id: 10,
        src: '/ankit_images/IMG_8319.JPG',
        title: 'Deep Blue',
        category: 'moody',
        description: 'The world drenched in midnight blue',
        aspectRatio: '4:3',
    },
    {
        id: 11,
        src: '/ankit_images/IMG_8331.JPG',
        title: 'Emerald Twilight',
        category: 'moody',
        description: 'Dark waters and muted greens at the edge of night',
        aspectRatio: '4:3',
    },
    {
        id: 12,
        src: '/ankit_images/IMG_8601.JPG',
        title: 'Vivid Earth',
        category: 'nature',
        description: 'Blue skies meeting the warm earth below',
        aspectRatio: '4:3',
    },
    {
        id: 13,
        src: '/ankit_images/IMG_8883_jpg.JPG',
        title: 'Warm Dusk',
        category: 'moody',
        description: 'Evening settles in with golden undertones',
        aspectRatio: '4:3',
    },
];

export const categories: { value: PhotoCategory; label: string }[] = [
    { value: 'all', label: 'All' },
    { value: 'nature', label: 'Nature' },
    { value: 'travel', label: 'Travel' },
    { value: 'moody', label: 'Moody' },
    { value: 'portrait', label: 'Portrait' },
];
